### ISSUE TITLE
Found 0 WiiMote devices when paired to Balance Board

### ISSUE THREAD

**Issue by ryanbartley** [rpavlik/wiiuse#65]
Mac OSX 10.10.4 
MacBook Pro
Wii Fit Balance Board - Device Name: Nintendo RVL-WBC-01
using master branch.

Even though my computer is connected to the device, I can't "find" the board. Tried a number of things, and read through these problems here...https://github.com/rpavlik/wiiuse/issues/42 and here https://github.com/rpavlik/wiiuse/issues/10 but nothings helped.

**Comment by janoc** [comment]
Hello, 

What exactly do you mean by "Even though my computer is connected to the device, I can't "find" the board." ? 

If the machine is connected already, Wiimote/Board stop being discoverable, so that could be normal behaviour. I have never used Wiiuse on Mac so I am not sure what is the normal way to connect the board there. 

In Linux you have to press the sync button and then launch the Wiiuse application and it will connect. In Windows you usually need to connect beforehand using the Windows Bluetooth utility and then the Wiiuse examples will find the board.

J.

**Comment by ryanbartley** [comment]
What I mean is that i didn't know the board had to be disconnected from the computer in order to be discoverable and therefore connected by the library. Is that the case? I figured it was similar to the way you describe the windows scenario. Just wondering what the order of operation is and if people have gotten the balance board to work with the library on MacOSX. Thanks for getting back so fast!

Ryan

**Comment by janoc** [comment]
I think on Mac the board should be disconnected before you run the application - i.e. put the board in discoverable mode by pressing the sync button (the one next to the battery, not the large one at the front!) and then run the application. Do not connect the Wiimote to Mac OS X beforehand - Wiiuse is doing active search for the Wiimote and will not find it in such case.

However, the board is known to be flaky with the current Wiiuse (some people reported "stuck sensor" problems), so I am interested to know whether or not it will work for you. For me both a 3rd party Big Ben made board and a genuine Nintendo one were working OK in Linux.

**Comment by ryanbartley** [comment]
Just tested on osx and it works. Thanks so much for getting back to me! I have one other question. If you turn off the application, it remains connected to the computer as a bluetooth device, which in turn does not allow for reconnect when the application restarts. Is there a way to remove the bluetooth device connection on exit (slash) a way to find a wiimote device from a bluetooth "connected" list?

**Comment by janoc** [comment]
I am glad to hear that it works. 

Normally the Wiimote/board will automatically shut down when the application is closed, however, I don't know how it is implemented for Mac as I don't have one (this is very platform-specific stuff). Otherwise the device should turn itself off and disconnect from the host after a while of being idle, but that could depends on the version of Wiimote/board you have. 

There isn't an easy way to "find" an already connected device. Wiimote stops being discoverable once it is connected and that's why Wiiuse will not see it. We could potentially try to connect without doing the discovery first - that would probably succeed if the device is connected already - however, that will find the Wiimote/board in an indeterminate state. There isn't really a good way to reinitialize a Wiimote (it was designed to reset on new connection), so this would most likely cause problems, especially with expansions. 

Moreover, this is again platform-specific - e.g. Windows and Mac leave it connected as you describe because the system HID driver keeps it open (the system sees it as a game controller). Linux disconnects the device as soon as the device is closed by the application because it connect to it as to a gamepad and there is nothing (=driver) to keep the connection open once the Wiiuse application closes.  So the code would have to be done for each supported platform separately. It is a situation with no good solutions, I am afraid.

**Comment by ryanbartley** [comment]
Thanks for such a thorough explanation. I really appreciate it. I'll let you know if I find anything through my explorations.

**Comment by janoc** [comment]
Well, if you figure something out, a patch would be very appreciated, because neither me nor Ryan have a Mac available for development, so any improvements on that platform have to come from outside.
