### ISSUE TITLE
Wrong battery level

### ISSUE THREAD

**Issue by Guitayk** [rpavlik/wiiuse#90]
I have a problem with the battery level. Indeed, when I used battery level, that returned me something close to 1.4*10^-45.
I tried again with batteries wich are new and I had the same result.
I primary thought it was a problem of conversion (I would like to set the battery level in a QProgressBar) but I tried other things and I always get this number.
Do you have any idea of the origin of the problem ?

PS : Sorry for my English level, I'm still really bad even if I'm learnig it since 8 years.

**Comment by janoc** [comment]
Hello, 

That looks like a 0 to me, for all practical purposes. Your Wiimote either has a dead battery (the measurement is very approximate in the hardware!) or is simply reporting an invalid value in the status report. Is that a genuine Nintendo Wiimote? What is the Bluetooth device name of it?

Also, could you build a debug version and post the logs of the traffic the wiiuse command line example prints out? That would permit to verify whether the Wiimote is sending correct data. The status report is requested and sent several times, look for a string of bytes like this:

20 BB BB LF 00 00 VV

You are interested in the last byte (VV), that is the battery level.

**Comment by Guitayk** [comment]
I do not really understood what you meaned by "genuine Nintendo Wiimote" :/ For the name it's : Nintendo RVL-CNT-01. 

For the second part of your message, I'm sorry but I don't know how I can do that. Can I do this direclty whit QT ? Or should I use an other software ?

**Comment by Guitayk** [comment]
I'm compiling with QT, and I think I do not succed to use CMake properly. I'm starting with "advanced" programmation and I never used CMake before. 
He gave me a CMakeFIles folder with inside a CMakeOutput.log. Is it that ?

Otherwise, I could give you the debug folder which is generated by my compiler.

**Comment by janoc** [comment]
What do you mean by "compiling with QT"? Are you using Qt Creator?

>He gave me a CMakeFIles folder with inside a CMakeOutput.log. Is it that ?

No. 

>Otherwise, I could give you the debug folder which is generated by my compiler.

That would be completely useless as I cannot run your code and I don't have your Wiimote. I need the **output** produced by the example program when running with your controller.

Here you have a manual showing how to specify the build settings when using CMake in QtCreator:
http://doc.qt.io/qtcreator/creator-build-settings.html (under the "CMake Build Configuration" section). Note the CMAKE_BUILD_TYPE being set to Debug - that is what you need. 

Once you have that, compile the Wiiuse example program and run it. And then post the output here.

**Comment by Guitayk** [comment]
Yeah I'm using QT Creator
Okay I think I had an old version of QT that why I do not find the options of the doc. I update it and i will check that just after

**Comment by Guitayk** [comment]
I have to much problems with QT this evening, I will check that tommorow. Thanks for you help today ^^

**Comment by Guitayk** [comment]
Finally after a lot of problems with my QT, wiiuse make it crash. Indeed, when I use a wiiuse function ( like wiiuse_find ), my program compile and start but it instantly crashs with the following error : 0xc0000135.
I can't anymore launch my program and try to use cmake. Do you have an id of the origin of the probelm.
PS : The following line do not make it crash : wiimote_t** wiimote;

**Comment by janoc** [comment]
On Fri, Jul 21, 2017 at 10:43 PM, Guitayk <notifications@github.com> wrote:

> Finally after a lot of problems with my QT, wiiuse make it crash. Indeed,
> when I use a wiiuse function ( like wiiuse_find ), my program compile and
> start but it instantly crashs with the following error : 0xc0000135.
> I can't anymore launch my program and try to use cmake. Do you have an id
> of the origin of the probelm.
> PS : The following line do not make it crash : wiimote_t** wiimote;
>

I am sorry, no.

Without seeing your program I don't have the slightest clue about what you
are doing wrong. However, I have asked you to run the example program that
is included in Wiiuse, not something of your own.

The instructions how to compile the library, including the passing the
CMake parameters from command line (so that you don't have to fight with Qt
Creator!) are on the Wiiuse home page.

The output of the example program when compiled in debug mode looks similar
to this:

wiiuse v0.15.0 loaded.
  Fork at http://github.com/rpavlik/wiiuse
  Original By: Michael Laforest <thepara[at]gmail{dot}com> http://wiiuse.net
[DEBUG] /Users/jeremy/projects/wiiuse/src/os_mac/os_mac_find.m:200:
Found a wiimote
[DEBUG] /Users/jeremy/projects/wiiuse/src/os_mac/os_mac_find.m:211:
Inquiry complete, error=0, aborted=NO
[DEBUG] /Users/jeremy/projects/wiiuse/src/os_mac/os_mac_find.m:211:
Inquiry complete, error=0, aborted=YES
[ERROR] Unable to stop bluetooth device inquiry.
[INFO] Found Wiimote (40-d2-8a-b6-0a-47) [id 1]
[INFO] Found 1 Wiimote device(s).
[DEBUG] /Users/jeremy/projects/wiiuse/src/os_mac/os_mac_interface.m:80:
Connecting to Wiimote [id 1].
[INFO] Connected to Wiimote [id 1].
[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:356: Setting report
type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30
[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:560: Writing 1
bytes to memory location 0x4a400f0...
Write data is: 55
[DEBUG] (id 1) SEND: (16) 04 a4 00 f0 01 55 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00
[DEBUG] /Users/jeremy/projects/wiiuse/src/io.c:275: Wiimote reset!

[DEBUG] (id 1) SEND: (17) 00 00 00 16 00 08
[DEBUG] (id 1) RECV: (30) 00 00
[DEBUG] (id 1) RECV: (22) 00 00 16 07
[DEBUG] /Users/jeremy/projects/wiiuse/src/io.c:140: (id 1) dropping
report 0x22, waiting for 0x21
[DEBUG] (id 1) RECV: (21) 00 00 70 00 16 80 80 7f 32 9a 98 98 0d 00 00
00 00 00 00 00 00
[DEBUG] /Users/jeremy/projects/wiiuse/src/io.c:293: Calibrated wiimote acc

[DEBUG] /Users/jeremy/projects/wiiuse/src/io.c:316: Asking for status,
attempt 0 ...

[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:505: Requested
wiimote status.
[DEBUG] (id 1) SEND: (15) 00
[DEBUG] (id 1) RECV: (20) 00 00 00 00 00 80
[DEBUG] /Users/jeremy/projects/wiiuse/src/io.c:316: Asking for status,
attempt 1 ...

[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:505: Requested
wiimote status.
[DEBUG] (id 1) SEND: (15) 00
[DEBUG] (id 1) RECV: (20) 00 00 00 00 00 80


Yours will be likely a bit different, which is normal. Here you can see
also how a status request looks like - the last line is the reply from the
Wiimote, battery level is 0x80 which corresponds to 0x80/0xC8 = 0.64, 64%
battery level.

Without that I cannot help you, I am sorry.

**Comment by Guitayk** [comment]
I didn't understand this my bad.
I will do that.

**Comment by Guitayk** [comment]
I'm probably stupid but I do not understand anything. Well I think I will give up for the moment because I don't make it. So thanks for the time you accord me and sorry for this waste of time.

**Comment by janoc** [comment]
You are welcome. If you manage to compile the example program at some point, I am still interested in its output - you could have found a new bug.

**Comment by Guitayk** [comment]
I do not understand any part of CMake.
So I try to compile the examlpe with an other IDE. But I get  30 errors like this: 

||=== Build: Debug in test (compiler: GNU GCC Compiler) ===|
P:\Programmation\C++\test\main.c||In function 'handle_event':|
P:\Programmation\C++\test\main.c|130|warning: implicit declaration of function 'wiiuse_set_motion_plus' [-Wimplicit-function-declaration]|
P:\Programmation\C++\test\main.c|169|error: 'EXP_MOTION_PLUS_NUNCHUK' undeclared (first use in this function)|
P:\Programmation\C++\test\main.c|169|note: each undeclared identifier is reported only once for each function it appears in|
P:\Programmation\C++\test\main.c|187|error: 'struct joystick_t' has no member named 'x'|
P:\Programmation\C++\test\main.c|187|error: 'struct joystick_t' has no member named 'y'|
P:\Programmation\C++\test\main.c|286|error: 'EXP_WII_BOARD' undeclared (first use in this function)|
P:\Programmation\C++\test\main.c|288|error: 'wii_board_t' undeclared (first use in this function)|
P:\Programmation\C++\test\main.c|288|error: expected expression before ')' token|
P:\Programmation\C++\test\main.c|289|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|289|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|289|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|289|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|290|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|290|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|291|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|291|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|293|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|293|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|293|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|293|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|294|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|294|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|294|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|294|error: dereferencing pointer to incomplete type|
P:\Programmation\C++\test\main.c|297|error: 'EXP_MOTION_PLUS' undeclared (first use in this function)|
P:\Programmation\C++\test\main.c|300|error: 'const struct expansion_t' has no member named 'mp'|
P:\Programmation\C++\test\main.c|301|error: 'const struct expansion_t' has no member named 'mp'|
P:\Programmation\C++\test\main.c|302|error: 'const struct expansion_t' has no member named 'mp'|
P:\Programmation\C++\test\main.c||In function 'any_wiimote_connected':|
P:\Programmation\C++\test\main.c|391|warning: implicit declaration of function 'WIIMOTE_IS_CONNECTED' [-Wimplicit-function-declaration]|
P:\Programmation\C++\test\main.c||In function 'main':|
P:\Programmation\C++\test\main.c|550|error: 'WIIUSE_WII_BOARD_CTRL_INSERTED' undeclared (first use in this function)|
P:\Programmation\C++\test\main.c|560|error: 'WIIUSE_MOTION_PLUS_ACTIVATED' undeclared (first use in this function)|
P:\Programmation\C++\test\main.c|567|error: 'WIIUSE_WII_BOARD_CTRL_REMOVED' undeclared (first use in this function)|
P:\Programmation\C++\test\main.c|568|error: 'WIIUSE_MOTION_PLUS_REMOVED' undeclared (first use in this function)|
||=== Build failed: 30 error(s), 2 warning(s) (0 minute(s), 0 second(s)) ===|

**Comment by janoc** [comment]
You are obviously missing some #include lines when the compiler is complaining about undeclared symbols. That is basic C/C++, switching between IDEs will not solve that for you, the IDE has no way to know what you want to do.  I cannot do this work for you, sorry.

Anyhow, I have asked you to compile the program that comes with wiiuse in the wiiuse/example folder. Not some random piece of code that you wrote. The example program included with Wiiuse is known to both compile correctly and to work so I can be sure that any problems you may have are either due to Wiiuse or the hardware, not bugs in your code. You only have to follow the instructions on the main Wiiuse Github page. 

If you don't understand anything about CMake, there are plenty of tutorials online showing how to use it. Again, that's not something you can expect me to teach you here.

**Comment by Guitayk** [comment]
But this is the example wich is in the wiiuse/example folder :/
And I do not touch anything of it. So maybe the problem is in the example ?
And I will check again for tutorials about CMake because I obviously need one, but I'm not sure I will totally understand it :/

**Comment by Guitayk** [comment]
There is two folders with example in their name. Is it the example folder or the example-sdl one ?

**Comment by janoc** [comment]
If it is an example in the Wiiuse folder, then why is the path:
>P:\Programmation\C++\test\main.c

Did you just copy the file out of the Wiiuse distribution? Why? You don't realize that that will NOT compile like that? Why don't you follow the compilation instructions for Wiiuse posted here: https://github.com/rpavlik/wiiuse  and do something else instead?

**Comment by janoc** [comment]
>There is two folders with example in their name. Is it the example folder or the example-sdl one ?

You need the program from the example folder. But that is normally compiled when you build Wiiuse, you don't have to compile it separately.

**Comment by Guitayk** [comment]
Because I'm on Windows and the part about Windows do not describe anything about the steps I need to do.

> Windows:

The CMake GUI can be used to generate a Visual Studio solution.

You need the install the Windows DDK (driver development kit) to compile wiiuse. You can download this from here: http://www.microsoft.com/whdc/devtools/ddk/default.mspx

You might also need to install the latest Windows SDK.

**Comment by janoc** [comment]
Because in Windows the procedure is more-or-less the same. You run cmake-gui, configure the project so that it finds all dependencies and CMake will generate you a project for Visual Studio or makefiles for nmake (depends on what you select at the start).

**Comment by janoc** [comment]
Here is a quick tutorial showing how to build programs for Windows using CMake and Visual Studio:
https://cognitivewaves.wordpress.com/cmake-and-visual-studio/

The new Visual Studio 2017 has a rudimentary CMake support but I don't recommend using it - it is more trouble than it is worth.

**Comment by Guitayk** [comment]
OKay I finally used CMake (I think) (It was easier with line input than with the GUI)
Now I have Project.cbp (I selected Code-Blocks MinGW) But when I open it, main.c is charged, CMakeLists.txt also, but I still have error of compilation.

**Comment by janoc** [comment]
I don't think you will be able to compile it in Windows with anything else but Visual Studio because it depends on some low level things from the Platform SDK related to Bluetooth - which MinGW doesn't have access to.

**Comment by Guitayk** [comment]
Ok I will try this tomorow, thanks for your patience !

**Comment by Guitayk** [comment]
But before all my problems with QT, my program was able to be connect to my wiimote, make it rumble and it was with MinGW. So maybe it is the origin of the problem of battery level !

**Comment by janoc** [comment]
>But before all my problems with QT, my program was able to be connect to my wiimote, make it rumble and it was with MinGW. So maybe it is the origin of the problem of battery level !

I don't understand what  are you talking about. Whether you are using MinGW or Visual Studio is completely irrelevant to your supposed battery problem. Once you have a compiled version of Wiiuse, you can use even MinGW, it doesn't matter. However, to compile *Wiiuse itself* in Windows only Visual Studio is supported because of the system dependencies. 

The battery state being reported wrong could be a problem of your Wiimote, it could be some protocol error/bug in Wiiuse or it could be a bug in your code. 

I cannot speculate about what your code does because I don't have it and don't want to debug it, so I am asking you to run the known working example code to be able to conclusively rule out that it is a hardware or Wiiuse problem *under known (to me) conditions* What is so difficult to understand on this concept?

If you are not willing or able to do what I am asking you to do, I will be forced to close this issue because we are only wasting time here.

**Comment by Guitayk** [comment]
Okay so yeah I will close it because I do not succed to do what you asked me  to do. So thanks for the time you accorded me.
